--[[
    VAL VEHICLE SHOP - Vehicle Image Configuration
    
    ใช้ไฟล์นี้เพื่อกำหนดรูปภาพสำหรับรถแต่ละคัน
    Format: ['model'] = 'image_url'
    
    ตัวอย่างการใช้งาน:
    - ใช้ URL รูปภาพจากเว็บ
    - ใช้ path รูปภาพในโฟลเดอร์ html/images/
    
    หมายเหตุ: 
    - ถ้าไม่กำหนดรูปภาพ จะแสดง icon รถเริ่มต้น
    - รองรับ format: .png, .jpg, .jpeg, .webp, .gif
]]

Config = Config or {}

Config.VehicleImages = {
    -- =====================================
    -- CYCLES (จักรยาน)
    -- =====================================
    ['bmx']         = 'html/images/vehicles/bmx.png',
    ['cruiser']     = 'html/images/vehicles/cruiser.png',
    ['fixter']      = 'html/images/vehicles/fixter.png',
    ['scorcher']    = 'html/images/vehicles/scorcher.png',
    ['tribike']     = 'html/images/vehicles/tribike.png',
    ['tribike2']    = 'html/images/vehicles/tribike2.png',
    ['tribike3']    = 'html/images/vehicles/tribike3.png',

    -- =====================================
    -- MOTORCYCLES (มอเตอร์ไซค์)
    -- =====================================
    ['akuma']       = 'html/images/vehicles/akuma.png',
    ['avarus']      = 'html/images/vehicles/avarus.png',
    ['bagger']      = 'html/images/vehicles/bagger.png',
    ['bati']        = 'html/images/vehicles/bati.png',
    ['bati2']       = 'html/images/vehicles/bati2.png',
    ['bf400']       = 'html/images/vehicles/bf400.png',
    ['carbonrs']    = 'html/images/vehicles/carbonrs.png',
    ['chimera']     = 'html/images/vehicles/chimera.png',
    ['cliffhanger'] = 'html/images/vehicles/cliffhanger.png',
    ['daemon']      = 'html/images/vehicles/daemon.png',
    ['daemon2']     = 'html/images/vehicles/daemon2.png',
    ['defiler']     = 'html/images/vehicles/defiler.png',
    ['diablous']    = 'html/images/vehicles/diablous.png',
    ['diablous2']   = 'html/images/vehicles/diablous2.png',
    ['double']      = 'html/images/vehicles/double.png',
    ['enduro']      = 'html/images/vehicles/enduro.png',
    ['esskey']      = 'html/images/vehicles/esskey.png',
    ['faggio']      = 'html/images/vehicles/faggio.png',
    ['faggio2']     = 'html/images/vehicles/faggio2.png',
    ['faggio3']     = 'html/images/vehicles/faggio3.png',
    ['fcr']         = 'html/images/vehicles/fcr.png',
    ['fcr2']        = 'html/images/vehicles/fcr2.png',
    ['gargoyle']    = 'html/images/vehicles/gargoyle.png',
    ['hakuchou']    = 'html/images/vehicles/hakuchou.png',
    ['hakuchou2']   = 'html/images/vehicles/hakuchou2.png',
    ['hexer']       = 'html/images/vehicles/hexer.png',
    ['innovation']  = 'html/images/vehicles/innovation.png',
    ['lectro']      = 'html/images/vehicles/lectro.png',
    ['manchez']     = 'html/images/vehicles/manchez.png',
    ['nemesis']     = 'html/images/vehicles/nemesis.png',
    ['nightblade']  = 'html/images/vehicles/nightblade.png',
    ['oppressor']   = 'html/images/vehicles/oppressor.png',
    ['oppressor2']  = 'html/images/vehicles/oppressor2.png',
    ['pcj']         = 'html/images/vehicles/pcj.png',
    ['ratbike']     = 'html/images/vehicles/ratbike.png',
    ['ruffian']     = 'html/images/vehicles/ruffian.png',
    ['sanchez']     = 'html/images/vehicles/sanchez.png',
    ['sanchez2']    = 'html/images/vehicles/sanchez2.png',
    ['sanctus']     = 'html/images/vehicles/sanctus.png',
    ['shotaro']     = 'html/images/vehicles/shotaro.png',
    ['sovereign']   = 'html/images/vehicles/sovereign.png',
    ['thrust']      = 'html/images/vehicles/thrust.png',
    ['vader']       = 'html/images/vehicles/vader.png',
    ['vindicator']  = 'html/images/vehicles/vindicator.png',
    ['vortex']      = 'html/images/vehicles/vortex.png',
    ['wolfsbane']   = 'html/images/vehicles/wolfsbane.png',
    ['zombiea']     = 'html/images/vehicles/zombiea.png',
    ['zombieb']     = 'html/images/vehicles/zombieb.png',

    -- =====================================
    -- SPORTS (รถสปอร์ต)
    -- =====================================
    ['adm_porcaygt2']       = 'html/images/vehicles/adm_porcaygt2.png',
    ['alpha']       = 'html/images/vehicles/alpha.png',
    ['banshee']     = 'html/images/vehicles/banshee.png',
    ['bestiagts']   = 'html/images/vehicles/bestiagts.png',
    ['buffalo']     = 'html/images/vehicles/buffalo.png',
    ['buffalo2']    = 'html/images/vehicles/buffalo2.png',
    ['buffalo3']    = 'html/images/vehicles/buffalo3.png',
    ['carbonizzare'] = 'html/images/vehicles/carbonizzare.png',
    ['comet2']      = 'html/images/vehicles/comet2.png',
    ['comet3']      = 'html/images/vehicles/comet3.png',
    ['comet4']      = 'html/images/vehicles/comet4.png',
    ['comet5']      = 'html/images/vehicles/comet5.png',
    ['coquette']    = 'html/images/vehicles/coquette.png',
    ['cypher']      = 'html/images/vehicles/cypher.png',
    ['drafter']     = 'html/images/vehicles/drafter.png',
    ['elegy']       = 'html/images/vehicles/elegy.png',
    ['elegy2']      = 'html/images/vehicles/elegy2.png',
    ['feltzer2']    = 'html/images/vehicles/feltzer2.png',
    ['feltzer3']    = 'html/images/vehicles/feltzer3.png',
    ['flashgt']     = 'html/images/vehicles/flashgt.png',
    ['furoregt']    = 'html/images/vehicles/furoregt.png',
    ['fusilade']    = 'html/images/vehicles/fusilade.png',
    ['futo']        = 'html/images/vehicles/futo.png',
    ['gb200']       = 'html/images/vehicles/gb200.png',
    ['growler']     = 'html/images/vehicles/growler.png',
    ['hotring']     = 'html/images/vehicles/hotring.png',
    ['imorgon']     = 'html/images/vehicles/imorgon.png',
    ['issi7']       = 'html/images/vehicles/issi7.png',
    ['italigto']    = 'html/images/vehicles/italigto.png',
    ['jester']      = 'html/images/vehicles/jester.png',
    ['jester2']     = 'html/images/vehicles/jester2.png',
    ['jester3']     = 'html/images/vehicles/jester3.png',
    ['jester4']     = 'html/images/vehicles/jester4.png',
    ['khamelion']   = 'html/images/vehicles/khamelion.png',
    ['komoda']      = 'html/images/vehicles/komoda.png',
    ['kuruma']      = 'html/images/vehicles/kuruma.png',
    ['kuruma2']     = 'html/images/vehicles/kuruma2.png',
    ['locust']      = 'html/images/vehicles/locust.png',
    ['lynx']        = 'html/images/vehicles/lynx.png',
    ['massacro']    = 'html/images/vehicles/massacro.png',
    ['massacro2']   = 'html/images/vehicles/massacro2.png',
    ['neo']         = 'html/images/vehicles/neo.png',
    ['neon']        = 'html/images/vehicles/neon.png',
    ['ninef']       = 'html/images/vehicles/ninef.png',
    ['ninef2']      = 'html/images/vehicles/ninef2.png',
    ['omnis']       = 'html/images/vehicles/omnis.png',
    ['paragon']     = 'html/images/vehicles/paragon.png',
    ['paragon2']    = 'html/images/vehicles/paragon2.png',
    ['pariah']      = 'html/images/vehicles/pariah.png',
    ['penumbra']    = 'html/images/vehicles/penumbra.png',
    ['penumbra2']   = 'html/images/vehicles/penumbra2.png',
    ['raiden']      = 'html/images/vehicles/raiden.png',
    ['rapidgt']     = 'html/images/vehicles/rapidgt.png',
    ['rapidgt2']    = 'html/images/vehicles/rapidgt2.png',
    ['raptor']      = 'html/images/vehicles/raptor.png',
    ['revolter']    = 'html/images/vehicles/revolter.png',
    ['ruston']      = 'html/images/vehicles/ruston.png',
    ['schafter3']   = 'html/images/vehicles/schafter3.png',
    ['schafter4']   = 'html/images/vehicles/schafter4.png',
    ['schafter5']   = 'html/images/vehicles/schafter5.png',
    ['schafter6']   = 'html/images/vehicles/schafter6.png',
    ['schlagen']    = 'html/images/vehicles/schlagen.png',
    ['schwarzer']   = 'html/images/vehicles/schwarzer.png',
    ['sentinel3']   = 'html/images/vehicles/sentinel3.png',
    ['seven70']     = 'html/images/vehicles/seven70.png',
    ['specter']     = 'html/images/vehicles/specter.png',
    ['specter2']    = 'html/images/vehicles/specter2.png',
    ['streiter']    = 'html/images/vehicles/streiter.png',
    ['sugoi']       = 'html/images/vehicles/sugoi.png',
    ['sultan']      = 'html/images/vehicles/sultan.png',
    ['sultan2']     = 'html/images/vehicles/sultan2.png',
    ['sultan3']     = 'html/images/vehicles/sultan3.png',
    ['surano']      = 'html/images/vehicles/surano.png',
    ['tropos']      = 'html/images/vehicles/tropos.png',
    ['verlierer2']  = 'html/images/vehicles/verlierer2.png',
    ['vstr']        = 'html/images/vehicles/vstr.png',
    ['zr350']       = 'html/images/vehicles/zr350.png',

    -- =====================================
    -- SUPER (รถซุปเปอร์คาร์)
    -- =====================================
    ['adder']       = 'html/images/vehicles/adder.png',
    ['autarch']     = 'html/images/vehicles/autarch.png',
    ['banshee2']    = 'html/images/vehicles/banshee2.png',
    ['bullet']      = 'html/images/vehicles/bullet.png',
    ['cheetah']     = 'html/images/vehicles/cheetah.png',
    ['cheetah2']    = 'html/images/vehicles/cheetah2.png',
    ['cyclone']     = 'html/images/vehicles/cyclone.png',
    ['deveste']     = 'html/images/vehicles/deveste.png',
    ['emerus']      = 'html/images/vehicles/emerus.png',
    ['entityxf']    = 'html/images/vehicles/entityxf.png',
    ['entity2']     = 'html/images/vehicles/entity2.png',
    ['fmj']         = 'html/images/vehicles/fmj.png',
    ['furia']       = 'html/images/vehicles/furia.png',
    ['gp1']         = 'html/images/vehicles/gp1.png',
    ['infernus']    = 'html/images/vehicles/infernus.png',
    ['italigtb']    = 'html/images/vehicles/italigtb.png',
    ['italigtb2']   = 'html/images/vehicles/italigtb2.png',
    ['krieger']     = 'html/images/vehicles/krieger.png',
    ['le7b']        = 'html/images/vehicles/le7b.png',
    ['nero']        = 'html/images/vehicles/nero.png',
    ['nero2']       = 'html/images/vehicles/nero2.png',
    ['osiris']      = 'html/images/vehicles/osiris.png',
    ['penetrator']  = 'html/images/vehicles/penetrator.png',
    ['pfister811']  = 'html/images/vehicles/pfister811.png',
    ['prototipo']   = 'html/images/vehicles/prototipo.png',
    ['reaper']      = 'html/images/vehicles/reaper.png',
    ['s80']         = 'html/images/vehicles/s80.png',
    ['sc1']         = 'html/images/vehicles/sc1.png',
    ['scramjet']    = 'html/images/vehicles/scramjet.png',
    ['sultanrs']    = 'html/images/vehicles/sultanrs.png',
    ['t20']         = 'html/images/vehicles/t20.png',
    ['taipan']      = 'html/images/vehicles/taipan.png',
    ['tempesta']    = 'html/images/vehicles/tempesta.png',
    ['tezeract']    = 'html/images/vehicles/tezeract.png',
    ['thrax']       = 'html/images/vehicles/thrax.png',
    ['tigon']       = 'html/images/vehicles/tigon.png',
    ['turismor']    = 'html/images/vehicles/turismor.png',
    ['tyrant']      = 'html/images/vehicles/tyrant.png',
    ['tyrus']       = 'html/images/vehicles/tyrus.png',
    ['vacca']       = 'html/images/vehicles/vacca.png',
    ['vagner']      = 'html/images/vehicles/vagner.png',
    ['vigilante']   = 'html/images/vehicles/vigilante.png',
    ['visione']     = 'html/images/vehicles/visione.png',
    ['voltic']      = 'html/images/vehicles/voltic.png',
    ['voltic2']     = 'html/images/vehicles/voltic2.png',
    ['xa21']        = 'html/images/vehicles/xa21.png',
    ['zentorno']    = 'html/images/vehicles/zentorno.png',
    ['zorrusso']    = 'html/images/vehicles/zorrusso.png',

    -- =====================================
    -- SEDANS (รถเก๋ง)
    -- =====================================
    ['asea']        = 'html/images/vehicles/asea.png',
    ['asea2']       = 'html/images/vehicles/asea2.png',
    ['asterope']    = 'html/images/vehicles/asterope.png',
    ['cog55']       = 'html/images/vehicles/cog55.png',
    ['cog552']      = 'html/images/vehicles/cog552.png',
    ['cognoscenti'] = 'html/images/vehicles/cognoscenti.png',
    ['cognoscenti2'] = 'html/images/vehicles/cognoscenti2.png',
    ['emperor']     = 'html/images/vehicles/emperor.png',
    ['emperor2']    = 'html/images/vehicles/emperor2.png',
    ['emperor3']    = 'html/images/vehicles/emperor3.png',
    ['fugitive']    = 'html/images/vehicles/fugitive.png',
    ['glendale']    = 'html/images/vehicles/glendale.png',
    ['glendale2']   = 'html/images/vehicles/glendale2.png',
    ['ingot']       = 'html/images/vehicles/ingot.png',
    ['intruder']    = 'html/images/vehicles/intruder.png',
    ['premier']     = 'html/images/vehicles/premier.png',
    ['primo']       = 'html/images/vehicles/primo.png',
    ['primo2']      = 'html/images/vehicles/primo2.png',
    ['regina']      = 'html/images/vehicles/regina.png',
    ['romero']      = 'html/images/vehicles/romero.png',
    ['schafter2']   = 'html/images/vehicles/schafter2.png',
    ['stafford']    = 'html/images/vehicles/stafford.png',
    ['stanier']     = 'html/images/vehicles/stanier.png',
    ['stratum']     = 'html/images/vehicles/stratum.png',
    ['stretch']     = 'html/images/vehicles/stretch.png',
    ['superd']      = 'html/images/vehicles/superd.png',
    ['surge']       = 'html/images/vehicles/surge.png',
    ['tailgater']   = 'html/images/vehicles/tailgater.png',
    ['tailgater2']  = 'html/images/vehicles/tailgater2.png',
    ['warrener']    = 'html/images/vehicles/warrener.png',
    ['warrener2']   = 'html/images/vehicles/warrener2.png',
    ['washington']  = 'html/images/vehicles/washington.png',

    -- =====================================
    -- SUVs (รถ SUV)
    -- =====================================
    ['baller']      = 'html/images/vehicles/baller.png',
    ['baller2']     = 'html/images/vehicles/baller2.png',
    ['baller3']     = 'html/images/vehicles/baller3.png',
    ['baller4']     = 'html/images/vehicles/baller4.png',
    ['baller5']     = 'html/images/vehicles/baller5.png',
    ['baller6']     = 'html/images/vehicles/baller6.png',
    ['bjxl']        = 'html/images/vehicles/bjxl.png',
    ['cavalcade']   = 'html/images/vehicles/cavalcade.png',
    ['cavalcade2']  = 'html/images/vehicles/cavalcade2.png',
    ['contender']   = 'html/images/vehicles/contender.png',
    ['dubsta']      = 'html/images/vehicles/dubsta.png',
    ['dubsta2']     = 'html/images/vehicles/dubsta2.png',
    ['dubsta3']     = 'html/images/vehicles/dubsta3.png',
    ['fq2']         = 'html/images/vehicles/fq2.png',
    ['granger']     = 'html/images/vehicles/granger.png',
    ['granger2']    = 'html/images/vehicles/granger2.png',
    ['gresley']     = 'html/images/vehicles/gresley.png',
    ['habanero']    = 'html/images/vehicles/habanero.png',
    ['huntley']     = 'html/images/vehicles/huntley.png',
    ['landstalker'] = 'html/images/vehicles/landstalker.png',
    ['landstalker2'] = 'html/images/vehicles/landstalker2.png',
    ['mesa']        = 'html/images/vehicles/mesa.png',
    ['mesa2']       = 'html/images/vehicles/mesa2.png',
    ['mesa3']       = 'html/images/vehicles/mesa3.png',
    ['novak']       = 'html/images/vehicles/novak.png',
    ['patriot']     = 'html/images/vehicles/patriot.png',
    ['patriot2']    = 'html/images/vehicles/patriot2.png',
    ['radi']        = 'html/images/vehicles/radi.png',
    ['rebla']       = 'html/images/vehicles/rebla.png',
    ['rocoto']      = 'html/images/vehicles/rocoto.png',
    ['seminole']    = 'html/images/vehicles/seminole.png',
    ['seminole2']   = 'html/images/vehicles/seminole2.png',
    ['serrano']     = 'html/images/vehicles/serrano.png',
    ['toros']       = 'html/images/vehicles/toros.png',
    ['xls']         = 'html/images/vehicles/xls.png',
    ['xls2']        = 'html/images/vehicles/xls2.png',

    -- =====================================
    -- COUPES (รถ Coupe)
    -- =====================================
    ['cogcabrio']   = 'html/images/vehicles/cogcabrio.png',
    ['exemplar']    = 'html/images/vehicles/exemplar.png',
    ['f620']        = 'html/images/vehicles/f620.png',
    ['felon']       = 'html/images/vehicles/felon.png',
    ['felon2']      = 'html/images/vehicles/felon2.png',
    ['jackal']      = 'html/images/vehicles/jackal.png',
    ['oracle']      = 'html/images/vehicles/oracle.png',
    ['oracle2']     = 'html/images/vehicles/oracle2.png',
    ['sentinel']    = 'html/images/vehicles/sentinel.png',
    ['sentinel2']   = 'html/images/vehicles/sentinel2.png',
    ['windsor']     = 'html/images/vehicles/windsor.png',
    ['windsor2']    = 'html/images/vehicles/windsor2.png',
    ['zion']        = 'html/images/vehicles/zion.png',
    ['zion2']       = 'html/images/vehicles/zion2.png',

    -- =====================================
    -- MUSCLE (รถ Muscle)
    -- =====================================
    ['blade']       = 'html/images/vehicles/blade.png',
    ['buccaneer']   = 'html/images/vehicles/buccaneer.png',
    ['buccaneer2']  = 'html/images/vehicles/buccaneer2.png',
    ['chino']       = 'html/images/vehicles/chino.png',
    ['chino2']      = 'html/images/vehicles/chino2.png',
    ['clique']      = 'html/images/vehicles/clique.png',
    ['coquette3']   = 'html/images/vehicles/coquette3.png',
    ['deviant']     = 'html/images/vehicles/deviant.png',
    ['dominator']   = 'html/images/vehicles/dominator.png',
    ['dominator2']  = 'html/images/vehicles/dominator2.png',
    ['dominator3']  = 'html/images/vehicles/dominator3.png',
    ['dominator4']  = 'html/images/vehicles/dominator4.png',
    ['dominator5']  = 'html/images/vehicles/dominator5.png',
    ['dominator6']  = 'html/images/vehicles/dominator6.png',
    ['dukes']       = 'html/images/vehicles/dukes.png',
    ['dukes2']      = 'html/images/vehicles/dukes2.png',
    ['dukes3']      = 'html/images/vehicles/dukes3.png',
    ['ellie']       = 'html/images/vehicles/ellie.png',
    ['faction']     = 'html/images/vehicles/faction.png',
    ['faction2']    = 'html/images/vehicles/faction2.png',
    ['faction3']    = 'html/images/vehicles/faction3.png',
    ['gauntlet']    = 'html/images/vehicles/gauntlet.png',
    ['gauntlet2']   = 'html/images/vehicles/gauntlet2.png',
    ['gauntlet3']   = 'html/images/vehicles/gauntlet3.png',
    ['gauntlet4']   = 'html/images/vehicles/gauntlet4.png',
    ['gauntlet5']   = 'html/images/vehicles/gauntlet5.png',
    ['hermes']      = 'html/images/vehicles/hermes.png',
    ['hotknife']    = 'html/images/vehicles/hotknife.png',
    ['hustler']     = 'html/images/vehicles/hustler.png',
    ['impaler']     = 'html/images/vehicles/impaler.png',
    ['impaler2']    = 'html/images/vehicles/impaler2.png',
    ['impaler3']    = 'html/images/vehicles/impaler3.png',
    ['impaler4']    = 'html/images/vehicles/impaler4.png',
    ['imperator']   = 'html/images/vehicles/imperator.png',
    ['imperator2']  = 'html/images/vehicles/imperator2.png',
    ['imperator3']  = 'html/images/vehicles/imperator3.png',
    ['lurcher']     = 'html/images/vehicles/lurcher.png',
    ['moonbeam']    = 'html/images/vehicles/moonbeam.png',
    ['moonbeam2']   = 'html/images/vehicles/moonbeam2.png',
    ['nightshade']  = 'html/images/vehicles/nightshade.png',
    ['peyote2']     = 'html/images/vehicles/peyote2.png',
    ['phoenix']     = 'html/images/vehicles/phoenix.png',
    ['picador']     = 'html/images/vehicles/picador.png',
    ['ratloader']   = 'html/images/vehicles/ratloader.png',
    ['ratloader2']  = 'html/images/vehicles/ratloader2.png',
    ['ruiner']      = 'html/images/vehicles/ruiner.png',
    ['ruiner2']     = 'html/images/vehicles/ruiner2.png',
    ['ruiner3']     = 'html/images/vehicles/ruiner3.png',
    ['sabregt']     = 'html/images/vehicles/sabregt.png',
    ['sabregt2']    = 'html/images/vehicles/sabregt2.png',
    ['slamvan']     = 'html/images/vehicles/slamvan.png',
    ['slamvan2']    = 'html/images/vehicles/slamvan2.png',
    ['slamvan3']    = 'html/images/vehicles/slamvan3.png',
    ['slamvan4']    = 'html/images/vehicles/slamvan4.png',
    ['slamvan5']    = 'html/images/vehicles/slamvan5.png',
    ['slamvan6']    = 'html/images/vehicles/slamvan6.png',
    ['stalion']     = 'html/images/vehicles/stalion.png',
    ['stalion2']    = 'html/images/vehicles/stalion2.png',
    ['tampa']       = 'html/images/vehicles/tampa.png',
    ['tampa2']      = 'html/images/vehicles/tampa2.png',
    ['tampa3']      = 'html/images/vehicles/tampa3.png',
    ['tulip']       = 'html/images/vehicles/tulip.png',
    ['vamos']       = 'html/images/vehicles/vamos.png',
    ['vigero']      = 'html/images/vehicles/vigero.png',
    ['virgo']       = 'html/images/vehicles/virgo.png',
    ['virgo2']      = 'html/images/vehicles/virgo2.png',
    ['virgo3']      = 'html/images/vehicles/virgo3.png',
    ['voodoo']      = 'html/images/vehicles/voodoo.png',
    ['voodoo2']     = 'html/images/vehicles/voodoo2.png',
    ['yosemite']    = 'html/images/vehicles/yosemite.png',
    ['yosemite2']   = 'html/images/vehicles/yosemite2.png',
    ['yosemite3']   = 'html/images/vehicles/yosemite3.png',

    -- =====================================
    -- COMPACTS (รถ Compact)
    -- =====================================
    ['blista']      = 'html/images/vehicles/blista.png',
    ['blista2']     = 'html/images/vehicles/blista2.png',
    ['blista3']     = 'html/images/vehicles/blista3.png',
    ['brioso']      = 'html/images/vehicles/brioso.png',
    ['brioso2']     = 'html/images/vehicles/brioso2.png',
    ['dilettante']  = 'html/images/vehicles/dilettante.png',
    ['dilettante2'] = 'html/images/vehicles/dilettante2.png',
    ['issi2']       = 'html/images/vehicles/issi2.png',
    ['issi3']       = 'html/images/vehicles/issi3.png',
    ['issi4']       = 'html/images/vehicles/issi4.png',
    ['issi5']       = 'html/images/vehicles/issi5.png',
    ['issi6']       = 'html/images/vehicles/issi6.png',
    ['kanjo']       = 'html/images/vehicles/kanjo.png',
    ['panto']       = 'html/images/vehicles/panto.png',
    ['prairie']     = 'html/images/vehicles/prairie.png',
    ['rhapsody']    = 'html/images/vehicles/rhapsody.png',

    -- =====================================
    -- OFF-ROAD (รถออฟโรด)
    -- =====================================
    ['bfinjection'] = 'html/images/vehicles/bfinjection.png',
    ['bifta']       = 'html/images/vehicles/bifta.png',
    ['blazer']      = 'html/images/vehicles/blazer.png',
    ['blazer2']     = 'html/images/vehicles/blazer2.png',
    ['blazer3']     = 'html/images/vehicles/blazer3.png',
    ['blazer4']     = 'html/images/vehicles/blazer4.png',
    ['blazer5']     = 'html/images/vehicles/blazer5.png',
    ['bodhi2']      = 'html/images/vehicles/bodhi2.png',
    ['brawler']     = 'html/images/vehicles/brawler.png',
    ['caracara']    = 'html/images/vehicles/caracara.png',
    ['caracara2']   = 'html/images/vehicles/caracara2.png',
    ['dloader']     = 'html/images/vehicles/dloader.png',
    ['dubsta3']     = 'html/images/vehicles/dubsta3.png',
    ['dune']        = 'html/images/vehicles/dune.png',
    ['dune2']       = 'html/images/vehicles/dune2.png',
    ['dune3']       = 'html/images/vehicles/dune3.png',
    ['dune4']       = 'html/images/vehicles/dune4.png',
    ['dune5']       = 'html/images/vehicles/dune5.png',
    ['everon']      = 'html/images/vehicles/everon.png',
    ['freecrawler'] = 'html/images/vehicles/freecrawler.png',
    ['hellion']     = 'html/images/vehicles/hellion.png',
    ['insurgent']   = 'html/images/vehicles/insurgent.png',
    ['insurgent2']  = 'html/images/vehicles/insurgent2.png',
    ['insurgent3']  = 'html/images/vehicles/insurgent3.png',
    ['kalahari']    = 'html/images/vehicles/kalahari.png',
    ['kamacho']     = 'html/images/vehicles/kamacho.png',
    ['marshall']    = 'html/images/vehicles/marshall.png',
    ['menacer']     = 'html/images/vehicles/menacer.png',
    ['monster']     = 'html/images/vehicles/monster.png',
    ['monster3']    = 'html/images/vehicles/monster3.png',
    ['monster4']    = 'html/images/vehicles/monster4.png',
    ['monster5']    = 'html/images/vehicles/monster5.png',
    ['outlaw']      = 'html/images/vehicles/outlaw.png',
    ['rancherxl']   = 'html/images/vehicles/rancherxl.png',
    ['rancherxl2']  = 'html/images/vehicles/rancherxl2.png',
    ['rcbandito']   = 'html/images/vehicles/rcbandito.png',
    ['rebel']       = 'html/images/vehicles/rebel.png',
    ['rebel2']      = 'html/images/vehicles/rebel2.png',
    ['riata']       = 'html/images/vehicles/riata.png',
    ['sandking']    = 'html/images/vehicles/sandking.png',
    ['sandking2']   = 'html/images/vehicles/sandking2.png',
    ['technical']   = 'html/images/vehicles/technical.png',
    ['technical2']  = 'html/images/vehicles/technical2.png',
    ['technical3']  = 'html/images/vehicles/technical3.png',
    ['trophytruck'] = 'html/images/vehicles/trophytruck.png',
    ['trophytruck2'] = 'html/images/vehicles/trophytruck2.png',
    ['vagrant']     = 'html/images/vehicles/vagrant.png',
    ['verus']       = 'html/images/vehicles/verus.png',
    ['winky']       = 'html/images/vehicles/winky.png',
    ['yosemite']    = 'html/images/vehicles/yosemite.png',
    ['zhaba']       = 'html/images/vehicles/zhaba.png',

    -- =====================================
    -- VANS (รถตู้)
    -- =====================================
    ['bison']       = 'html/images/vehicles/bison.png',
    ['bison2']      = 'html/images/vehicles/bison2.png',
    ['bison3']      = 'html/images/vehicles/bison3.png',
    ['bobcatxl']    = 'html/images/vehicles/bobcatxl.png',
    ['boxville']    = 'html/images/vehicles/boxville.png',
    ['boxville2']   = 'html/images/vehicles/boxville2.png',
    ['boxville3']   = 'html/images/vehicles/boxville3.png',
    ['boxville4']   = 'html/images/vehicles/boxville4.png',
    ['boxville5']   = 'html/images/vehicles/boxville5.png',
    ['burrito']     = 'html/images/vehicles/burrito.png',
    ['burrito2']    = 'html/images/vehicles/burrito2.png',
    ['burrito3']    = 'html/images/vehicles/burrito3.png',
    ['burrito4']    = 'html/images/vehicles/burrito4.png',
    ['burrito5']    = 'html/images/vehicles/burrito5.png',
    ['camper']      = 'html/images/vehicles/camper.png',
    ['gburrito']    = 'html/images/vehicles/gburrito.png',
    ['gburrito2']   = 'html/images/vehicles/gburrito2.png',
    ['journey']     = 'html/images/vehicles/journey.png',
    ['minivan']     = 'html/images/vehicles/minivan.png',
    ['minivan2']    = 'html/images/vehicles/minivan2.png',
    ['paradise']    = 'html/images/vehicles/paradise.png',
    ['pony']        = 'html/images/vehicles/pony.png',
    ['pony2']       = 'html/images/vehicles/pony2.png',
    ['rumpo']       = 'html/images/vehicles/rumpo.png',
    ['rumpo2']      = 'html/images/vehicles/rumpo2.png',
    ['rumpo3']      = 'html/images/vehicles/rumpo3.png',
    ['speedo']      = 'html/images/vehicles/speedo.png',
    ['speedo2']     = 'html/images/vehicles/speedo2.png',
    ['speedo4']     = 'html/images/vehicles/speedo4.png',
    ['surfer']      = 'html/images/vehicles/surfer.png',
    ['surfer2']     = 'html/images/vehicles/surfer2.png',
    ['taco']        = 'html/images/vehicles/taco.png',
    ['youga']       = 'html/images/vehicles/youga.png',
    ['youga2']      = 'html/images/vehicles/youga2.png',
    ['youga3']      = 'html/images/vehicles/youga3.png',

    -- =====================================
    -- CLASSIC (รถคลาสสิก)
    -- =====================================
    ['coquette2']   = 'html/images/vehicles/coquette2.png',
    ['fagaloa']     = 'html/images/vehicles/fagaloa.png',
    ['feltzer3']    = 'html/images/vehicles/feltzer3.png',
    ['gt500']       = 'html/images/vehicles/gt500.png',
    ['infernus2']   = 'html/images/vehicles/infernus2.png',
    ['jb700']       = 'html/images/vehicles/jb700.png',
    ['jb7002']      = 'html/images/vehicles/jb7002.png',
    ['mamba']       = 'html/images/vehicles/mamba.png',
    ['manana']      = 'html/images/vehicles/manana.png',
    ['manana2']     = 'html/images/vehicles/manana2.png',
    ['michelli']    = 'html/images/vehicles/michelli.png',
    ['monroe']      = 'html/images/vehicles/monroe.png',
    ['nebula']      = 'html/images/vehicles/nebula.png',
    ['peyote']      = 'html/images/vehicles/peyote.png',
    ['peyote3']     = 'html/images/vehicles/peyote3.png',
    ['pigalle']     = 'html/images/vehicles/pigalle.png',
    ['rapidgt3']    = 'html/images/vehicles/rapidgt3.png',
    ['retinue']     = 'html/images/vehicles/retinue.png',
    ['retinue2']    = 'html/images/vehicles/retinue2.png',
    ['savestra']    = 'html/images/vehicles/savestra.png',
    ['stinger']     = 'html/images/vehicles/stinger.png',
    ['stingergt']   = 'html/images/vehicles/stingergt.png',
    ['stromberg']   = 'html/images/vehicles/stromberg.png',
    ['swinger']     = 'html/images/vehicles/swinger.png',
    ['torero']      = 'html/images/vehicles/torero.png',
    ['tornado']     = 'html/images/vehicles/tornado.png',
    ['tornado2']    = 'html/images/vehicles/tornado2.png',
    ['tornado3']    = 'html/images/vehicles/tornado3.png',
    ['tornado4']    = 'html/images/vehicles/tornado4.png',
    ['tornado5']    = 'html/images/vehicles/tornado5.png',
    ['tornado6']    = 'html/images/vehicles/tornado6.png',
    ['turismo2']    = 'html/images/vehicles/turismo2.png',
    ['viseris']     = 'html/images/vehicles/viseris.png',
    ['z190']        = 'html/images/vehicles/z190.png',
    ['ztype']       = 'html/images/vehicles/ztype.png',
}

-- =====================================
-- สามารถเพิ่ม URL รูปภาพจากเว็บได้
-- ตัวอย่าง:
-- ['adder'] = 'https://example.com/images/adder.png',
-- =====================================
